#include <stdio.h>

int main(void) {
    // Open a file for writing ("w" mode)
    // Warning: "w" mode overwrites the file if it already exists!
    FILE *file = fopen("greetings.txt", "w");
    
    if (file == NULL) {
        printf("Error: Could not open file.\n");
        return 1;
    }
    
    // Writing text to the file using fprintf (File Print Format)
    fprintf(file, "Hello, World!\n");
    fprintf(file, "This is my first file generated by C.\n");
    
    // ALWAYS close the file when you are done!
    fclose(file);
    
    printf("Successfully wrote to the file.\n");
    
    return 0;
}
